### ISSUE TITLE
Can i use this in C# WinForms?

### ISSUE THREAD

**Issue by ghost** [vpzed/Destiny2-API-Info#2]
Hey im new to this, i want to know if its possible to get the destiny 2 account information in c#, i did this "tutorial" and it works, but now its in the program postman, but i want to get the account information in my C# Project.
Could you help me?

**Comment by vpzed** [comment]
I'm not a C# developer, but there is a Destiny API Discord server and there are developers for many different programming languages on there.  Here is a 24 hour invite link https://discord.gg/n6GK8E

I haven't been coding for the Bungie API in several months but my open source links page has this repository for C# stuff so maybe it can help  https://github.com/BaileyMillerSSI/Destiny2Api

**Comment by omgphil** [comment]
Win forms are just the technology to build UI, as a C# dev, I suggest you dont use winforms, but WPF or something else

**Comment by vpzed** [comment]
Closing since it is not a Wiki issue
